import { ThemeProvider } from "@/components/theme-provider";
import AppSessionProvider from "@/providers/app-session-provider";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <AppSessionProvider>
            {children}
            <Toaster />
          </AppSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
